name: JUnit Test

on:
  push:
    branches:
      - master
      - wip/github-actions-testing

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
    - name: Compile source code
      run: javac -cp .;./lib/* src/**/*.java
      if: matrix.os == 'windows-2019'
    - name: Compile source code
      run: javac -cp .:./lib/* src/**/*.java
      if: matrix.os == 'ubuntu-latest'
    - name: Run JUnit tests
      run: java -cp .;./lib/*;./src/test/java;./src/main/java org.junit.runner.JUnitCore tests/*
      if: matrix.os == 'windows-2019'
    - name: Run JUnit tests
      run: java -cp .:./lib/*:./src/test/java:./src/main/java org.junit.runner.JUnitCore tests/*
      if: matrix.os == 'ubuntu-latest'
